# Generated by Django 4.1.3 on 2023-06-14 03:51

import app_feedback.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_request', models.IntegerField(verbose_name='Номер заявки')),
                ('organization', models.CharField(max_length=100, verbose_name='Компания')),
                ('product', models.CharField(max_length=100, verbose_name='Продукт')),
                ('error', models.CharField(max_length=100, verbose_name='Ошибка')),
                ('error_description', models.TextField(verbose_name='Текст ошибки')),
                ('urgency', models.CharField(choices=[('high', 'Высший'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=100, verbose_name='Срочность')),
                ('status', models.CharField(choices=[('done', 'Завершено'), ('pending', 'В процессе'), ('new', 'Новая заявка'), ('declined', 'Отклонено')], default='Новая заявка', max_length=100, verbose_name='Статус заявки')),
                ('date_of_issue', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления заявки')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('files', models.FileField(blank=True, null=True, upload_to=app_feedback.models.feedback_file_path, verbose_name='Прикрепленные файлы')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app_feedback.feedback', verbose_name='Заявка')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_feedback.feedback', verbose_name='Заявка')),
            ],
        ),
    ]
