# Generated by Django 4.1.3 on 2023-06-18 04:55

import app_feedback.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('target', models.CharField(choices=[('Благотворительность', 'Благотворительность'), ('Социальный проект', 'Социальный проект'), ('Волонтерство', 'Волонтерство')], default='charity', max_length=100, verbose_name='Тип помощи')),
                ('target_name', models.CharField(max_length=30, verbose_name='Тема')),
                ('target_description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('done', 'Завершено'), ('pending', 'В процессе'), ('new', 'На рассмотрении'), ('declined', 'Отклонено')], default='new', max_length=100, verbose_name='Статус заявки')),
                ('date_of_issue', models.DateField(auto_now_add=True, verbose_name='Дата поступления заявки')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('reserve_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Дополнительный номер телефона')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('cash_need', models.FloatField(blank=True, null=True, verbose_name='Необходимая сумма')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на помощь',
                'verbose_name_plural': 'Заявки на помощь',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос Ответ',
                'verbose_name_plural': 'Вопросы Ответы',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=55, verbose_name='Имя')),
                ('type_of_help', models.TextField(verbose_name='Чем может помочь')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, default='images/avatar/default/user.jpg', null=True, upload_to=app_feedback.models.user_directory_path, verbose_name='Аватарка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=16, verbose_name='Номер счета')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_feedback.feedback', verbose_name='Реквизит')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('files', models.FileField(blank=True, null=True, upload_to=app_feedback.models.feedback_file_path, verbose_name='Прикрепленные файлы')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app_feedback.feedback', verbose_name='Заявка')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_feedback.feedback', verbose_name='Заявка')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_of_donation', models.FloatField(verbose_name='Сумма доната')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доната')),
                ('requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_feedback.requisite', verbose_name='Донат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
    ]
