# Generated by Django 4.1.3 on 2023-06-18 03:43

import app_feedback.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос Ответ',
                'verbose_name_plural': 'Вопросы Ответы',
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Заявка на помощь', 'verbose_name_plural': 'Заявки на помощь'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='error',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='error_description',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='number_request',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='urgency',
        ),
        migrations.AddField(
            model_name='feedback',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='cash_need',
            field=models.FloatField(blank=True, null=True, verbose_name='Необходимая сумма'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='reserve_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Дополнительный номер телефона'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='target',
            field=models.CharField(choices=[('Благотворительность', 'Благотворительность'), ('Социальный проект', 'Социальный проект'), ('Волонтерство', 'Волонтерство')], default='charity', max_length=100, verbose_name='Тип помощи'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='target_description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='target_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Тема'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True, verbose_name='Дата поступления заявки'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('done', 'Завершено'), ('pending', 'В процессе'), ('new', 'На рассмотрении'), ('declined', 'Отклонено')], default='new', max_length=100, verbose_name='Статус заявки'),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=55, verbose_name='Имя волонтера')),
                ('type_of_help', models.TextField(verbose_name='Чем может помочь')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, default='images/avatar/default/user.jpg', null=True, upload_to=app_feedback.models.user_directory_path, verbose_name='Аватарка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=16, verbose_name='Номер счета')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_feedback.feedback', verbose_name='Реквизит')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_of_donation', models.FloatField(verbose_name='Сумма доната')),
                ('requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_feedback.requisite', verbose_name='Донат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
    ]
