# Generated by Django 4.1.3 on 2023-06-18 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0002_questionanswer_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата доната'),
        ),
    ]
