# Generated by Django 4.1.3 on 2023-06-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0003_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='number_request',
        ),
    ]
