# Generated by Django 4.1.3 on 2023-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0004_remove_feedback_number_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('done', 'Завершено'), ('pending', 'В процессе'), ('new', 'Новая заявка'), ('declined', 'Отклонено')], default='new', max_length=100, verbose_name='Статус заявки'),
        ),
    ]
