# Generated by Django 4.1.3 on 2023-06-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0005_alter_feedback_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='error',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='error_description',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='target',
            field=models.CharField(choices=[('charity', 'Благотворительность'), ('social_project', 'Социальный проект')], default='new', max_length=100, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='target_description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('done', 'Завершено'), ('pending', 'В процессе'), ('new', 'На рассмотрении'), ('declined', 'Отклонено')], default='new', max_length=100, verbose_name='Статус заявки'),
        ),
    ]
