# Generated by Django 4.1.3 on 2023-06-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0007_application_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос Ответ',
                'verbose_name_plural': 'Вопросы Ответы',
            },
        ),
    ]
