# Generated by Django 4.1.3 on 2023-06-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0008_feedback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='target_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Тема'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='target',
            field=models.CharField(choices=[('charity', 'Благотворительность'), ('social_project', 'Социальный проект'), ('volunteering', 'Волонтерство')], default='new', max_length=100, verbose_name='Тип помощи'),
        ),
    ]
