# Generated by Django 4.1.3 on 2023-06-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0009_feedback_target_name_alter_feedback_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='cash_need',
            field=models.FloatField(blank=True, null=True, verbose_name='Необходимая сумма'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='reserve_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Дополнительный номер телефона'),
        ),
    ]
