# Generated by Django 4.1.3 on 2023-06-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0010_feedback_address_feedback_cash_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True, verbose_name='Дата поступления заявки'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
