# Generated by Django 4.1.3 on 2023-06-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0008_questionanswer'),
        ('app_feedback', '0011_alter_feedback_date_of_issue_and_more'),
    ]

    operations = [
    ]
