# Generated by Django 4.1.3 on 2023-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0012_merge_20230617_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='target',
            field=models.CharField(choices=[('charity', 'Благотворительность'), ('social_project', 'Социальный проект'), ('volunteering', 'Волонтерство')], default='charity', max_length=100, verbose_name='Тип помощи'),
        ),
    ]
