# Generated by Django 4.1.3 on 2023-06-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0007_alter_feedback_options'),
        ('app_feedback', '0012_merge_20230617_1801'),
    ]

    operations = [
    ]
