# Generated by Django 4.1.3 on 2023-06-17 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_feedback', '0013_merge_20230617_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=55, verbose_name='Имя волонтера')),
                ('type_of_help', models.TextField(verbose_name='Чем может помочь')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
        migrations.RemoveField(
            model_name='applicationcomments',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationcomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='applicationfiles',
            name='application',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='target',
            field=models.CharField(choices=[('Благотворительность', 'Благотворительность'), ('Социальный проект', 'Социальный проект'), ('Волонтерство', 'Волонтерство')], default='new', max_length=100, verbose_name='Тип помощи'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ApplicationComments',
        ),
        migrations.DeleteModel(
            name='ApplicationFiles',
        ),
    ]
