# Generated by Django 4.1.3 on 2023-06-17 17:09

import app_feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0015_volunteer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='image',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar/default/user.png', null=True, upload_to=app_feedback.models.user_directory_path, verbose_name='Аватарка'),
        ),
    ]
