# Generated by Django 4.1.3 on 2023-06-17 17:15

import app_feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0016_remove_volunteer_image_volunteer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar/default/user.jpg', null=True, upload_to=app_feedback.models.user_directory_path, verbose_name='Аватарка'),
        ),
    ]
