# Generated by Django 4.1.3 on 2023-06-18 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0017_alter_feedback_image'),
        ('app_feedback', '0017_alter_volunteer_avatar'),
    ]

    operations = [
    ]
