# Generated by Django 4.1.3 on 2023-06-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_remove_user_organization_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
